### ISSUE TITLE
Toggles for login and push to different repositories

### ISSUE THREAD

**Issue by staticaland** [oslokommune/reusable-docker-build-push#30]
# Description

Add inputs that toggle login and push. Login and push should not be coupled.

## Breaking change

This will be a breaking change because it makes most sense to rename the existing inputs. We'll bump the major version, and write a changelog with update instructions.

Alternatively, the inputs are kept and we make a deprecation warning. This would require a complex `if` statement for the relevant steps. I think this should be avoided.

# Motivation

Some users need to authenticate with GHCR in order to build the Dockerfile (`FROM` instructions that use GHCR addresses).

**Comment by yngvark** [comment]
[Slack thread](https://oslokommune.slack.com/archives/CV9EGL9UG/p1696943999973269)
